export const exteriorOptions = [
  "craftsman design",
  "victorian design",
  "cape cod design",
  "colonial design",
  "tudor design",
  "modern design",
  "mediterranean design",
  "ranch-style design",
  "mid-century modern design",
  "vinyl windows",
  "metal windows",
  "wood windows",
  "dual pane windows",
  "corner lot",
  "large lot",
  "outdoor kitchen",
  "fenced-in backyard",
  "pool in backyard",
  "hot tub",
  "spa",
  "fire pit",
  "drought-tolerant landscaping",
  "accessory dwelling unit",
  "quiet neighborhood",
  "cul-de-sac street",
  "gated community",
  "solar panels",
  "front porch",
  "wood siding",
  "stucco finish",
  "smooth stucco finish",
  "metal siding",
  "exterior wall sconce lighting",
  "landscape lighting",
  "new roof",
  "asphalt shingle roof",
  "metal roof",
  "slate roof",
  "tile roof",
  "built-up roof",
  "membrane roof",
];
