export const exteriorOptions = [
  { category: "Accessory Structures", option: "attached accessory dwelling unit" },
  { category: "Accessory Structures", option: "detached accessory dwelling unit" },
  { category: "Accessory Structures", option: "guest house" },
  { category: "Accessory Structures", option: "pool house" },
  { category: "Accessory Structures", option: "shed" },
  { category: "Accessory Structures", option: "stables" },
  { category: "Community Features", option: "community clubhouse" },
  { category: "Community Features", option: "community dog run" },
  { category: "Community Features", option: "community fitness center" },
  { category: "Community Features", option: "community golf course" },
  { category: "Community Features", option: "community park" },
  { category: "Community Features", option: "community playground" },
  { category: "Community Features", option: "gated community" },
  { category: "Community Features", option: "near schools" },
  { category: "Community Features", option: "near shops and restaurants" },
  { category: "Community Features", option: "walkable community" },
  { category: "Garage", option: "attached garage" },
  { category: "Garage", option: "basement garage" },
  { category: "Garage", option: "detached garage" },
  { category: "Lot", option: "corner lot" },
  { category: "Lot", option: "cul-de-sac lot" },
  { category: "Lot", option: "large lot" },
  { category: "Landscape", option: "concrete back patio" },
  { category: "Landscape", option: "concrete front patio" },
  { category: "Landscape", option: "drought-tolerant landscaping" },
  { category: "Landscape", option: "fencing around yard" },
  { category: "Landscape", option: "fire pit" },
  { category: "Landscape", option: "fruit trees" },
  { category: "Landscape", option: "garden" },
  { category: "Landscape", option: "landscape lighting" },
  { category: "Landscape", option: "outdoor grill" },
  { category: "Landscape", option: "outdoor fireplace" },
  { category: "Landscape", option: "outdoor kitchen" },
  { category: "Landscape", option: "wood deck" },
  { category: "Green Features", option: "gray water system" },
  { category: "Green Features", option: "rooftop solar panels" },
  { category: "Pool", option: "above-ground pool" },
  { category: "Pool", option: "infinity pool" },
  { category: "Pool", option: "lap pool" },
  { category: "Pool", option: "hot tub" },
  { category: "Pool", option: "pool" },
  { category: "Pool", option: "spa" },
  { category: "Architectural Design", option: "A-frame design" },
  { category: "Architectural Design", option: "Bungalow design" },
  { category: "Architectural Design", option: "Cabin design" },
  { category: "Architectural Design", option: "Cape Cod design" },
  { category: "Architectural Design", option: "Colonial design" },
  { category: "Architectural Design", option: "Contemporary design" },
  { category: "Architectural Design", option: "Craftsman design" },
  { category: "Architectural Design", option: "Mid-century Modern design" },
  { category: "Architectural Design", option: "Mediterranean design" },
  { category: "Architectural Design", option: "Modern design" },
  { category: "Architectural Design", option: "Ranch-style design" },
  { category: "Architectural Design", option: "Traditional design" },
  { category: "Architectural Design", option: "Tudor design" },
  { category: "Architectural Design", option: "Victorian design" },  
  { category: "Roof Types", option: "composition roof" },
  { category: "Roof Types", option: "concrete tile roof" },
  { category: "Roof Types", option: "copper roof" },
  { category: "Roof Types", option: "green roof" },
  { category: "Roof Types", option: "membrane roof" },
  { category: "Roof Types", option: "metal roof" },
  { category: "Roof Types", option: "rooftop solar panels" },
  { category: "Roof Types", option: "shingle roof" },
  { category: "Roof Types", option: "slate roof" },
  { category: "Exterior Finishes", option: "brick finish" },
  { category: "Exterior Finishes", option: "cement siding" },
  { category: "Exterior Finishes", option: "log exterior finish" },
  { category: "Exterior Finishes", option: "metal siding" },
  { category: "Exterior Finishes", option: "smooth stucco finish" },
  { category: "Exterior Finishes", option: "stone exterior finish" },
  { category: "Exterior Finishes", option: "stucco finish" },
  { category: "Exterior Finishes", option: "wood siding" },
  { category: "Exterior Finishes", option: "vinyl siding" },
  { category: "Windows", option: "dual pane windows" },
  { category: "Windows", option: "metal windows" },
  { category: "Windows", option: "triple pane windows" },
  { category: "Windows", option: "vinyl windows" },
  { category: "Windows", option: "wood windows" },
  { category: "Views", option: "canyon views" },
  { category: "Views", option: "city skyline views" },
  { category: "Views", option: "garden views" },
  { category: "Views", option: "golf course views" },
  { category: "Views", option: "lake views" },
  { category: "Views", option: "mountain views" },
  { category: "Views", option: "ocean views" },
  { category: "Outdoor Spaces", option: "back porch" },
  { category: "Outdoor Spaces", option: "balcony" },
  { category: "Outdoor Spaces", option: "courtyard" },
  { category: "Outdoor Spaces", option: "front porch" },
  { category: "Outdoor Spaces", option: "wrap around balcony" },
  { category: "Outdoor Spaces", option: "wrap around porch" },
];
