export const interiorOptions = [
  "renovated interior",
  "renovated kitchen",
  "renovated bath",
  "new construction",
  "hardwood flooring",
  "engineered wood flooring",
  "laminate wood flooring",
  "tile flooring",
  "concrete flooring",
  "tile flooring in bath",
  "tile flooring in kitchen",
  "chef’s kitchen",
  "eat-in kitchen",
  "dining room",
  "marble countertops",
  "granite countertops",
  "quartz countertops",
  "dedicated home office",
  "home theater",
  "home gym",
  "finished basement",
  "stainless steel appliances",
  "central air conditioning",
  "central heating",
  "walk-in closet in primary bedroom",
  "walk-in closet in all bedrooms",
  "city skyline views",
  "mountain views",
  "golf course views",
  "lake views",
  "ocean views",
  "garden views",
  "canyon views",
  "electric vehicle charger",
  "laundry room",
  "walk-in kitchen pantry",
  "ceiling fans",
  "built-in storage",
  "security system",
  "underfloor heating",
  "wood-burning fireplace",
  "gas fireplace",
  "wine fridge",
  "barn doors",
  "shaker cabinets",
  "farmhouse sink in kitchen",
];
