export const interiorOptions = [
  { category: "Basement", option: "finished dwelling unit" },
  { category: "Basement", option: "finished basement" },
  { category: "Basement", option: "unfinished basement" },
  { category: "Bathroom Features", option: "bidet in bath" },
  { category: "Bathroom Features", option: "double vanity in primary bath" },
  { category: "Bathroom Features", option: "private toilet room" },
  { category: "Bathroom Features", option: "linen closet in bath" },
  { category: "Bathroom Features", option: "multiple shower heads in primary bath" },
  { category: "Bathroom Features", option: "tub and shower in bath" },
  { category: "Bathroom Features", option: "separate tub and shower in bath" },
  { category: "Bathroom Features", option: "soaking tub in bath" },
  { category: "Construction", option: "new construction" },
  { category: "Construction", option: "renovated bath" },
  { category: "Construction", option: "renovated kitchen" },
  { category: "Construction", option: "renovated, turn-key interior" },
  { category: "Cooling", option: "ceiling fans" },
  { category: "Cooling", option: "central air conditioning" },
  { category: "Cooling", option: "zoned cooling" },
  { category: "Flooring", option: "concrete flooring" },
  { category: "Flooring", option: "engineered wood flooring" },
  { category: "Flooring", option: "hardwood flooring" },
  { category: "Flooring", option: "laminate wood flooring" },
  { category: "Flooring", option: "tile flooring" },
  { category: "Flooring", option: "tile flooring in bath" },
  { category: "Flooring", option: "tile flooring in kitchen" },
  { category: "Green Features", option: "electric vehicle charger" },
  { category: "Green Features", option: "home battery for solar" },
  { category: "Green Features", option: "skylights" },
  { category: "Heating", option: "central heat" },
  { category: "Heating", option: "gas fireplace" },
  { category: "Heating", option: "underfloor heating" },
  { category: "Heating", option: "wood-burning fireplace" },
  { category: "Kitchen Features", option: "chef’s kitchen" },
  { category: "Kitchen Features", option: "eat-in kitchen" },
  { category: "Kitchen Features", option: "farmhouse sink in kitchen" },
  { category: "Kitchen Features", option: "flat panel cabinets" },
  { category: "Kitchen Features", option: "marble countertops in kitchen" },
  { category: "Kitchen Features", option: "granite countertops in kitchen" },
  { category: "Kitchen Features", option: "quartz countertops in kitchen" },
  { category: "Kitchen Features", option: "shaker cabinets" },
  { category: "Kitchen Features", option: "stainless steel appliances" },
  { category: "Kitchen Features", option: "wine fridge" },
  { category: "Security Features", option: "fire sprinkler system" },
  { category: "Security Features", option: "leased security system" },
  { category: "Security Features", option: "owned security system" },
  { category: "Unique Rooms", option: "dining room" },
  { category: "Unique Rooms", option: "home gym" },
  { category: "Unique Rooms", option: "home office" },
  { category: "Unique Rooms", option: "home theater" },
  { category: "Unique Rooms", option: "walk-in kitchen pantry" },
  { category: "Unique Rooms", option: "home theater" },
  { category: "Unique Rooms", option: "laundry room" },
  { category: "Unique Rooms", option: "sauna" },
  { category: "Unique Rooms", option: "walk-in closet in all bedrooms" },
  { category: "Unique Rooms", option: "walk-in closet in primary bedroom" },
]
