export const landOptions = [
  "large lot",
  "water-front lot",
  "flat lot",
  "gently sloping lot",
  "moderately sloping lot",
  "steeply sloping lot",
  "level building pad",
  "large flat building pad",
  "water meter on site",
  "well on site",
  "septic system",
  "leach field",
  "percolation test completed",
  "geotechnical report available",
  "all utilities available",
  "sewer nearby",
  "power nearby",
  "fire hydrant nearby",
  "gas lines nearby",
  "land survey included",
  "architectural plans included",
  "good soils",
  "adjacent street has curbs and gutters",
  "on paved street",
  "on dirt road",
  "panoramic views",
  "city skyline views",
  "mountain views",
  "golf course views",
  "lake views",
  "ocean views",
  "garden views",
  "canyon views",
  "allows manufactured home",
  "no HOA restrictions",
  "HOA restrictions",
  "CC&R's",
  "gated community",
  "zoned residential",
  "zoned commercial",
  "zoned mixed-use",
  "development opportunity",
];
