export const landOptions = [
  { category: "Community Features", option: "CC&R's" },
  { category: "Community Features", option: "community clubhouse" },
  { category: "Community Features", option: "community dog run" },
  { category: "Community Features", option: "community fitness center" },
  { category: "Community Features", option: "community golf course" },
  { category: "Community Features", option: "community park" },
  { category: "Community Features", option: "community playground" },
  { category: "Community Features", option: "gated community" },
  { category: "Community Features", option: "HOA restrictions" },
  { category: "Community Features", option: "near schools" },
  { category: "Community Features", option: "near shops and restaurants" },
  { category: "Community Features", option: "no HOA restrictions" },
  { category: "Community Features", option: "walkable community" },
  { category: "Design Work", option: "architectural plans available" },
  { category: "Design Work", option: "architectural plans included" },
  { category: "Design Work", option: "land survey available" },
  { category: "Design Work", option: "land survey included" },
  { category: "Design Work", option: "soils report available" },
  { category: "Design Work", option: "soils report included" },
  { category: "Fencing", option: "chainlink fencing" },
  { category: "Fencing", option: "fenced lot" },
  { category: "Fencing", option: "wood fencing" },
  { category: "Fencing", option: "stone site walls" },
  { category: "Lot", option: "corner lot" },
  { category: "Lot", option: "cul-de-sac lot" },
  { category: "Lot", option: "flat lot" },
  { category: "Lot", option: "large lot" },
  { category: "Lot", option: "water-front lot" },
  { category: "Road Access", option: "on dirt road" },
  { category: "Road Access", option: "on paved street" },
  { category: "Topography", option: "gently sloping lot" },
  { category: "Topography", option: "large flat building pad" },
  { category: "Topography", option: "level building pad" },
  { category: "Topography", option: "moderately sloping lot" },
  { category: "Topography", option: "steeply sloping lot" },
  { category: "Utilities", option: "all utilities available" },
  { category: "Utilities", option: "fire hydrant nearby" },
  { category: "Utilities", option: "percolation test completed" },
  { category: "Utilities", option: "leach field" },
  { category: "Utilities", option: "power nearby" },
  { category: "Utilities", option: "septic system" },
  { category: "Utilities", option: "sewer on site" },
  { category: "Utilities", option: "sewer nearby" },
  { category: "Utilities", option: "water meter on site" },
  { category: "Utilities", option: "water nearby" },
  { category: "Utilities", option: "well on site" },
  { category: "Views", option: "canyon views" },
  { category: "Views", option: "city skyline views" },
  { category: "Views", option: "garden views" },
  { category: "Views", option: "golf course views" },
  { category: "Views", option: "lake views" },
  { category: "Views", option: "mountain views" },
  { category: "Views", option: "ocean views" },
  { category: "Zoning", option: "allows manufactured home" },
  { category: "Zoning", option: "development opportunity" },
  { category: "Zoning", option: "zoned commercial" },
  { category: "Zoning", option: "zoned mixed-use" },
  { category: "Zoning", option: "zoned residential" },
]
