export const parkingOptions = [
  "1-car attached garage",
  "1-car detached garage",
  "2-car attached garage",
  "2-car detached garage",
  "3-car attached garage",
  "3-car detached garage",
  "4-car attached garage",
  "4-car detached garage",
  "1-car attached carport",
  "1-car detached carport",
  "2-car attached carport",
  "2-car detached carport",
  "1 uncovered, assigned space",
  "2 uncovered, assigned spaces",
];
